### ISSUE TITLE
Could you share Campus data?

### ISSUE THREAD

**Issue by edwardnguyen1705** [Varun-Tandon14/Implementation-of-the-paper-Cross-View-Tracking-for-Multi-Human-3D-Pose-Estimation-at-over-100-FPS#1]
Dear @Varun-Tandon14 ,

Thanks so much for sharing your great work.

I would like to try your code, but the data from the original repos has vanished. Could you share the Campus data?

I download the [Campus-data](https://campar.in.tum.de/Chair/MultiHumanPose), but it seems that camera params are incorrect.
[producePmat.txt](https://github.com/user-attachments/files/18245081/producePmat.txt)

Thanks so much for your time.

**Comment by Varun-Tandon14** [comment]
Hi @edwardnguyen1705, you are correct. The original OneDrive link does not seem to be working. Luckily, I still had the original dataset in my local storage. Please download the dataset from [here](https://drive.google.com/file/d/1aZ-Ld4ZcAe_qNkhVR53nFJogtc-9egip/view?usp=sharing). You should use the dataset from the link I provided to test the code. Hopefully, this should resolve the issue and the code should run as is.

Thanks for bringing it to my attention, I will also update my repo accordingly, Happy Holidays.

**Comment by edwardnguyen1705** [comment]
> Hi @edwardnguyen1705, you are correct. The original OneDrive link does not seem to be working. Luckily, I still had the original dataset in my local storage. Please download the dataset from [here](https://drive.google.com/file/d/1aZ-Ld4ZcAe_qNkhVR53nFJogtc-9egip/view?usp=sharing). You should use the dataset from the link I provided to test the code. Hopefully, this should resolve the issue and the code should run as is.
> 
> Thanks for bringing it to my attention, I will also update my repo accordingly, Happy Holidays.

Many thanks! I will try soon.
Happy Holidays!

**Comment by edwardnguyen1705** [comment]
Dear @Varun-Tandon14 ,
I have successfully run your code. However, if I use `detection.json` (or my own file) instead of `annotation_2d.json`, the code fails.

[poses_2d_estimated.json](https://github.com/user-attachments/files/18246346/poses_2d_estimated.json)

```bash
Load 6000 frames from ['Camera2', 'Camera0', 'Camera1']
Camera id Camera1 | location: [-624.05799093  524.73482644  194.73802149]
Camera id Camera2 | location: [1194.35610655 -180.38527374  197.33939117]
Camera id Camera0 | location: [ 177.48953318 -505.16959482  192.33559877]
  8%|█████████▌                                                                                                               | 475/6000 [00:00<00:05, 1068.74it/s]
Traceback (most recent call last):
  File "repos/xview_tracking_3dpose/track_3d/src/main.py", line 99, in <module>
    poses_3D_latest = get_latest_3D_poses_available_for_cur_timestamp(poses_3d_tss, ts_cur_frame, delta_time_threshold=delta_time_threshold)
  File "repos/xview_tracking_3dpose/track_3d/src/helper_funcs.py", line 148, in get_latest_3D_poses_available_for_cur_timestamp
    'velocity': get_velocity_at_this_timestamp_for_this_id_for_cur_timestamp(poses_3d_all_timestamps,
  File "repos/xview_tracking_3dpose/track_3d/src/helper_funcs.py", line 98, in get_velocity_at_this_timestamp_for_this_id_for_cur_timestamp
    if poses_3d_all_timestamps[this_timestamp][id_index]['id'] == id_latest_pose:
TypeError: 'NoneType' object is not subscriptable
```

I think in the real cases, the 2d pose estimation model will produce False Positives and False Negatives, so the code could fail. I will try to debug. Hope that you consider fixing issue in the latest update.
I greatly appreciate your time. Again, Happy Holidays!

**Comment by Varun-Tandon14** [comment]
Hi @edwardnguyen1705, 

I am happy the code is working as is with the annotation_2d.json file for you. I am also aware that the code would break in the real-world situations as you have highlighted. The code was written with all the assumptions and biases the authors made in the original paper. My main aim was to implement the algorithm missing in the original repo. 
Honestly, I also don't have plans to improve/fix the repo to cover real-world scenarios and edge cases soon. But I will try to help through this medium. Hopefully, I didn't write such a spaghetti code, that you can debug and achieve your application. 

Warm Regards.

**Comment by edwardnguyen1705** [comment]
> Hi @edwardnguyen1705,
> 
> I am happy the code is working as is with the annotation_2d.json file for you. I am also aware that the code would break in the real-world situations as you have highlighted. The code was written with all the assumptions and biases the authors made in the original paper. My main aim was to implement the algorithm missing in the original repo. Honestly, I also don't have plans to improve/fix the repo to cover real-world scenarios and edge cases soon. But I will try to help through this medium. Hopefully, I didn't write such a spaghetti code, that you can debug and achieve your application.
> 
> Warm Regards.

Dear @Varun-Tandon14 ,

I understand and really appreciate that you shared this repo. I will try to fix the issue, if after testing speed I see this method potential.

Warm Regards.

**Comment by Varun-Tandon14** [comment]
Thanks for your kind words. I hope you achieve your goal with the repo. I just wanted to let you know that I'm closing this issue as solved. In the future, please feel free to contact me if you have any further suggestions. In this way, I will also get a chance to improve my knowledge.
